version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly, day: monday, time: '06:00', timezone: Europe/Berlin }
    open-pull-requests-limit: 5
    commit-message: { prefix: 'ci' }
    groups:
      actions: { patterns: ['*'] }

  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly, day: monday, time: '06:00', timezone: Europe/Berlin }
    open-pull-requests-limit: 5
    commit-message: { prefix: 'chore(npm)' }
    groups:
      minor-und-patch: { update-types: ['minor', 'patch'] }
